MONTHS_MAPS = {"janvier" : '01', 
               "février": '02', 
               "fevrier": '02', 
               "mars": '03', 
               "avril": '04', 
               "mai": '05', 
               "juin": '06', 
               "juillet": '07', 
               "août": '08', 
               "aout": '08', 
               "septembre": '09', 
               "octobre": '10', 
               "novembre": '11', 
               "décembre": '12', 
               "decembre": '12',
               "janv.": '01' , 
               "janv": '01', 
               "fev.": '02', 
               "fev": '02', 
               "av.": '04', 
               "avr.": '04', 
               "av": '04', 
               "juil.": '07', 
               "juil": '07', 
               "sept.": '09', 
               "sept": '09', 
               "oct.": '10', 
               "oct": '10', 
               "nov.": '11', 
               "nov": '11', 
               "déc.": '12', 
               "dec.": '12', 
               "déc": '12', 
               "dec": '12'}


TEIHEADER = {
    "fileDesc": "".join(['<fileDesc><titleStmt><title xml:lang="fr">placeholder</title>',
                        "<author>Lectaurep</author>",
                        "<funder>Ministry of Higher Education, Research and Innovation</funder>",
                        "<respStmt>",
                        "<resp>Edited and encoded by</resp>",
                        "<persName><forename>Alix</forename><surname>Chagué</surname></persName>",
                        "</respStmt><respStmt>",
                        "<resp>Edited and encoded by</resp>",
                        "<persName><forename>Hugo</forename><surname>Scheithauer</surname></persName>",
                        "</respStmt><respStmt>",
                        "<resp>Transcription by</resp>",
                        "<orgName>Département du Minutier central des notaires de Paris</orgName>",
                        '</respStmt><respStmt><resp>Digitization by</resp>',
                        "<orgName>Archives nationales</orgName></respStmt></titleStmt>",
                        '<publicationStmt><authority>Lectaurep (Archives nationales, Inria)</authority><availability>',
                        '<licence target="https://creativecommons.org/licenses/by/4.0/">',
                        "<p>Distributed under a Creative Commons Attribution 4.0 International (CC BY 4.0)",
                        '</p></licence></availability><date when-iso="2020"/>',
                        "</publicationStmt><seriesStmt>",
                        '<title type="main">Répertoires de notaires de Paris</title>',
                        "</seriesStmt><sourceDesc><p/></sourceDesc></fileDesc>"]),
    "encodingDesc": "".join(["<encodingDesc><projectDesc>",
                             "<p xml:lang="fr">L'encodage de ce document s'est fait dans ",
                             "le cadre du projet LECTAUREP</p></projectDesc>",
                             "<editorialDecl><correction>",
                             '<p xml:lang="fr">Aucune correction</p></correction>',
                             '<hyphenation eol="all" rend="sh">',
                             "<p xml:lang="fr">Toutes les coupures de mots pour ",
                             "fin de ligne (indiquées principalement avec un tiret",
                             "simple) ont été conservées.</p>",
                             "</hyphenation></editorialDecl></encodingDesc>"])
}